version: '3.8'

services:
  app:
    image: neomediatech/update-ipsets:latest
    hostname: update-ipsets
    volumes:
      - data:/data
    environment:
      SLEEP: ${SLEEP:-600}
      ENV_IPSETS_APPLY: ${ENV_IPSETS_APPLY:-0}
    cap_add:
      - NET_ADMIN

  web:
    image: nginx:alpine
    hostname: web
    volumes:
      - web_data:/usr/share/nginx/html

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /folder/path/in/your/host

  web_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /another/folder/path/in/your/host

